trigger: 
  - master

pr: none

jobs:
- job: projectOnePRD
  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Enterprise'
      scriptLocation: 'scriptPath'
      scriptPath: './terraform.sh'
      arguments: EnterprisePRD-KV projectOnePRD-PRD
- job: ProjectOneUAT
  steps:
  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Enterprise'
      scriptLocation: 'scriptPath'
      scriptPath: './terraform.sh'
      arguments: EnterpriseDEV-KV ProjectOneUAT-DEV

